# Generated by Django 3.2.5 on 2022-01-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('course_pic', models.FileField(default='static/default_user.png', upload_to='static/uploads')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('message', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('coursework', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='static/results')),
                ('result_cycle', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=200, null=True)),
                ('module_name', models.CharField(max_length=200, null=True)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.courses')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('WEEK1', 'WEEK1'), ('WEEK2', 'WEEK2'), ('WEEK3', 'WEEK3'), ('WEEK4', 'WEEK4'), ('WEEK5', 'WEEK5'), ('WEEK6', 'WEEK6'), ('WEEK7', 'WEEK7'), ('WEEK8', 'WEEK8'), ('WEEK9', 'WEEK9'), ('WEEK10', 'WEEK10'), ('WEEK11', 'WEEK11')], max_length=100, null=True)),
                ('content', models.FileField(null=True, upload_to='static/uploads/modulecontent')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.courses')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.modules')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, null=True)),
                ('fee', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('WEEK1', 'WEEK1'), ('WEEK2', 'WEEK2'), ('WEEK3', 'WEEK3'), ('WEEK4', 'WEEK4'), ('WEEK5', 'WEEK5'), ('WEEK6', 'WEEK6'), ('WEEK7', 'WEEK7'), ('WEEK8', 'WEEK8'), ('WEEK9', 'WEEK9'), ('WEEK10', 'WEEK10'), ('WEEK11', 'WEEK11')], max_length=100, null=True)),
                ('assignment_file', models.FileField(null=True, upload_to='static/uploads/assignment')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.courses')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.modules')),
            ],
        ),
    ]
