# Generated by Django 3.2.5 on 2022-01-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_lecturermodule_studentmodule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturermodule',
            old_name='lecturer',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='StudentModule',
        ),
    ]
