# Generated by Django 3.2.5 on 2022-01-20 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0003_auto_20220120_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LecturerModule',
            new_name='UserModule',
        ),
    ]
