# Generated by Django 3.2.5 on 2022-01-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_rename_lecturermodule_usermodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='module_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_pic',
            field=models.FileField(default='static/default_user.png', null=True, upload_to='static/uploads'),
        ),
    ]
