# Generated by Django 3.2.5 on 2022-01-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_fees_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='clearance_date',
            field=models.DateField(null=True),
        ),
    ]
