from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_dashboard, name="admin_dashboard"),
    path('signup_students', views.signup_students, name="signup_students"),
    path('signup_lecturers', views.signup_lecturers, name="signup_lecturers"),
    path('signup_admins', views.signup_admins, name="signup_admins"),
    path('show_students', views.show_students, name='show_students'),
    path('show_lecturers', views.show_lecturers, name='show_lecturers'),
    path('show_admins', views.show_admins, name='show_admins'),
    path('profile_students/<str:username>', views.profile_students, name='profile_students'),
    path('profile_others/<str:username>', views.profile_others, name='profile_others'),
    path('show_results', views.show_results, name='show_results'),
    path('add_results', views.add_results, name='add_results'),
    path('show_detail_results/<str:studentid>', views.show_detail_results, name='show_detail_results'),
    path('add_results_manual', views.add_results_manual, name='add_results_manual'),
    path('delete_result/<str:studentid>', views.delete_results, name='delete_results'),
    path('show_results_all', views.show_results_all, name='show_results_all'),
    path('delete_result_by_id/<str:id>', views.delete_results_by_id, name='delete_results_by_id'),
    path('show_courses', views.show_courses, name='show_courses'),
    path('add_courses', views.add_courses, name='add_courses'),
    path('update_courses/<str:courseid>', views.update_courses, name='update_courses'),
    path('delete_courses/<str:courseid>', views.delete_courses, name='delete_courses'),
    path('show_modules', views.show_modules, name='show_modules'),
    path('add_modules', views.add_modules, name='add_modules'),
    path('update_modules/<str:moduleid>', views.update_modules, name='update_modules'),
    path('delete_modules/<str:moduleid>', views.delete_modules, name='delete_modules'),
    path('show_fees', views.show_fees, name='show_fees'),
    path('add_fees', views.add_fees, name='add_fees'),
    path('update_fees/<str:feeid>', views.update_fees, name='update_fees'),
    path('delete_fees/<str:feeid>', views.delete_fees, name='delete_fees'),
    path('delete_students/<str:username>', views.delete_students, name='delete_students'),
    path('delete_lecturers/<str:username>', views.delete_lecturers, name='delete_lecturers'),
    path('delete_admins/<str:username>', views.delete_admins, name='delete_admins'),

    path('show_enquiries', views.show_enquiries, name='show_enquiries'),

    path('show_module_access/<str:moduleid>', views.show_module_access, name='show_module_access'),
    path('add_module_access/<str:moduleid>', views.add_module_access, name='add_module_access'),
    path('delete_module_access/<str:moduleid>/<str:userid>', views.delete_module_access, name='delete_module_access'),
    path('show_module_details/<str:moduleid>', views.show_module_details, name='show_module_details'),
    path('add_contents/<str:moduleid>', views.add_contents, name='add_contents'),
    path('delete_contents/<str:id>', views.delete_contents, name='delete_contents'),
    path('add_assignments/<str:moduleid>', views.add_assignments, name='add_assignments'),
    path('delete_assignments/<str:id>', views.delete_assignments, name='delete_assignments'),
]